"""The Redis Streams adapter (ADR-002, ADR-062, ADR-067, ADR-068).

Pure translation between :class:`EventEnvelope` and Redis Streams, and nothing
else. Retry, leasing, ordering, routing and the dead-letter decision all live
elsewhere -- in :mod:`dhruva.contexts.platform.domain.messaging` and in the
relay -- and duplicating any of them here would give the platform two places to
change and one of them would be missed.

This module is the *only* place in the codebase that knows what a stream id is.
Boundary rule R9 (ADR-068) fails the build if a domain or strategy module
imports ``redis``, and the ack token below is deliberately opaque so a consumer
cannot begin to depend on the shape of one.

Why the stream id is generated by Redis, not derived from ``sequence``
----------------------------------------------------------------------
The S05 design proposed ``XADD`` with an explicit id derived from the outbox
``sequence``, so that a relay retry would be idempotent at the transport. It
cannot work, and the reason is worth recording where the code is.

Redis requires an explicitly supplied entry id to be **strictly greater than the
top of the stream**. Streams are per aggregate *type* and carry many aggregates,
while retry is per *message* (ADR-064): sequence 10 may fail, sequences 11 and
12 may succeed, and sequence 10 is then re-offered after them. ``XADD`` with
``10-0`` against a stream topped by ``12-0`` is refused. Falling back to a
generated id on refusal is worse than useless -- a generated id is a millisecond
timestamp, roughly 1.7e12, so a single fallback puts the stream top permanently
beyond every future ``sequence`` and *every* subsequent explicit id fails. The
scheme degrades to generated ids on first use, having added a silent mode.

Nothing is lost by dropping it. Transport-level de-duplication could never have
protected the consumer's side effect anyway, because it happens in a different
transaction from the work. ADR-065 puts the ledger write in the *same*
transaction as the effect it guards, which is strictly stronger. At-least-once
(ADR-062) already states that a duplicate is correct behaviour.

Why a malformed entry raises instead of being skipped
-----------------------------------------------------
ADR-022: ambiguity blocks rather than proceeds. An entry this adapter cannot
read is not skipped -- skipping would process the events around it and leave a
hole nobody sees. It raises, and because the entry was delivered under a
consumer group it stays in the pending list: recoverable with ``XAUTOCLAIM`` or
a re-read from ``0`` once a human has looked at it. Nothing is lost by stopping;
something is lost by continuing.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Final

from redis import exceptions as redis_errors

from dhruva.shared.errors import (
    ConfigurationError,
    DhruvaError,
    ExternalServiceError,
    UpstreamTimeoutError,
    UpstreamUnavailableError,
    ValidationError,
)
from dhruva.shared.messaging import Delivery, EventEnvelope

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping, Sequence
    from datetime import timedelta

    from redis.asyncio import Redis

    from dhruva.shared.messaging import AckToken

__all__ = [
    "DEFAULT_GROUP_NAMESPACE",
    "DEFAULT_MAXLEN",
    "DEFAULT_NAMESPACE",
    "ENVELOPE_FIELD",
    "RedisAck",
    "RedisEventStream",
    "RedisPublishResult",
    "RedisStreamPublisher",
    "stream_key",
]

#: Key prefix for event streams. One stream per aggregate type, so a consumer
#: subscribes to what concerns it rather than filtering a firehose.
DEFAULT_NAMESPACE: Final = "dhruva:events"

#: Key prefix for consumer groups, kept distinct from the stream namespace so a
#: `KEYS dhruva:events:*` in an incident does not also match group bookkeeping.
DEFAULT_GROUP_NAMESPACE: Final = "dhruva:cg"

#: Capped trimming length. The stream is a transport buffer, not storage: the
#: outbox is the source of truth (ADR-062), and a wiped Redis loses nothing that
#: has not already been published.
DEFAULT_MAXLEN: Final = 100_000

#: The single entry field holding the canonical envelope JSON. One field rather
#: than a field per envelope attribute, because the envelope's canonical form is
#: what ADR-061 versions -- spreading it would create a second wire format that
#: nothing validates.
ENVELOPE_FIELD: Final = "envelope"

#: Aggregate types that may appear in a key. Deliberately narrow: an aggregate
#: type carrying ``:`` would silently create a *different* stream than the one
#: intended, and one carrying ``*`` would match a glob some operator later runs.
_SAFE_AGGREGATE_TYPE: Final = re.compile(r"\A[A-Za-z][A-Za-z0-9_.-]{0,63}\Z")

#: Redis reports "no such consumer group" with this prefix. Matched as a string
#: because redis-py raises the generic `ResponseError` for it.
_NO_GROUP: Final = "NOGROUP"

#: Raised by `XGROUP CREATE` when the group already exists, which is the normal
#: outcome of an idempotent `ensure_group` and not a failure.
_BUSY_GROUP: Final = "BUSYGROUP"

#: `XAUTOCLAIM` replies with ``[cursor, entries]`` on Redis 6.2 and gained a
#: third element on Redis 7. Two is what this adapter needs and therefore what it
#: requires; a shorter reply is not a version difference, it is a reply from
#: something that is not Redis.
_XAUTOCLAIM_ELEMENTS: Final = 2


def stream_key(aggregate_type: str, *, namespace: str = DEFAULT_NAMESPACE) -> str:
    """Return the stream key for an aggregate type.

    Parameters
    ----------
    aggregate_type
        The routing value carried on the envelope (ADR-062). Persisted on the
        outbox row rather than inferred, so the stream is named after a recorded
        fact rather than a guess.
    namespace
        Key prefix, so a test and a production database can share one Redis.

    Raises
    ------
    ValidationError
        If the aggregate type could not appear in a key unambiguously. This is a
        terminal failure (ADR-064): retrying it twelve times produces twelve
        identical rejections.
    """
    if not _SAFE_AGGREGATE_TYPE.match(aggregate_type):
        raise ValidationError(
            "aggregate_type cannot be used in a Redis key",
            aggregate_type=aggregate_type,
            expected=_SAFE_AGGREGATE_TYPE.pattern,
        )
    return f"{namespace}:{aggregate_type}"


@dataclass(frozen=True, slots=True)
class RedisAck:
    """The opaque token acknowledging one delivery.

    Frozen, and never interpreted outside this module. A consumer that read the
    entry id out of one could branch on it, and would then be a consumer that
    cannot run against replay -- which is the whole of what ADR-067 protects.
    """

    stream: str
    entry_id: str


@dataclass(frozen=True, slots=True)
class RedisPublishResult:
    """One batch's outcome, satisfying the :class:`PublishResult` protocol."""

    accepted: Sequence[EventEnvelope]
    rejected: Sequence[tuple[EventEnvelope, Exception]]


class RedisStreamPublisher:
    """Writes envelopes to Redis Streams. Implements :class:`EventPublisher`.

    Parameters
    ----------
    client
        An ``redis.asyncio.Redis``. Injected rather than constructed here: the
        connection pool, TLS and credentials are composition-root concerns
        (ADR-033), and this class must not be able to read a password.
    namespace
        Stream key prefix.
    maxlen
        Capped trim length applied on every write, or ``None`` to never trim.
        Approximate by default, which is what makes it cheap.
    approximate
        Whether trimming may overshoot ``maxlen``. Exact trimming is O(N) in the
        amount removed and offers nothing: the outbox, not the stream, is the
        record.

    Notes
    -----
    One ``XADD`` per envelope rather than a pipeline. A pipeline would cost fewer
    round trips, but attributing a partial failure back to the exact envelope
    that caused it is what the relay needs in order to retry precisely, and a
    scheme where that attribution is subtle is a scheme that will one day retry
    the wrong message. Recorded as TD-S05-8; the batch is 100 and the budget
    (S05 design section 15) is per publish, so this is not on a hot path yet.
    """

    __slots__ = ("_approximate", "_client", "_maxlen", "_namespace")

    def __init__(
        self,
        client: Redis,
        *,
        namespace: str = DEFAULT_NAMESPACE,
        maxlen: int | None = DEFAULT_MAXLEN,
        approximate: bool = True,
    ) -> None:
        """Bind the publisher to a Redis client and a key namespace."""
        if maxlen is not None and maxlen <= 0:
            raise ConfigurationError(
                "maxlen must be positive or None; zero would trim every write away",
                maxlen=maxlen,
            )
        self._client = client
        self._namespace = namespace
        self._maxlen = maxlen
        self._approximate = approximate

    async def publish(self, envelopes: Sequence[EventEnvelope]) -> RedisPublishResult:
        """Write each envelope to the stream for its aggregate type.

        Never raises for an ordinary transport failure. A refused envelope is
        *reported* so the relay can schedule a retry for that one message; the
        alternative -- raising -- makes one bad message cost the whole batch.
        """
        accepted: list[EventEnvelope] = []
        rejected: list[tuple[EventEnvelope, Exception]] = []

        for envelope in envelopes:
            error = await self._write(envelope)
            if error is None:
                accepted.append(envelope)
            else:
                rejected.append((envelope, error))

        return RedisPublishResult(accepted=accepted, rejected=rejected)

    async def _write(self, envelope: EventEnvelope) -> Exception | None:
        """Write one envelope, returning the failure rather than raising it."""
        try:
            key = stream_key(envelope.aggregate_type, namespace=self._namespace)
        except ValidationError as error:
            return error

        try:
            await self._client.xadd(
                key,
                {ENVELOPE_FIELD: envelope.to_json()},
                maxlen=self._maxlen,
                approximate=self._approximate,
            )
        except redis_errors.RedisError as error:
            return _translate(error)
        except DhruvaError as error:
            # `to_json` refuses a payload it cannot encode exactly (ADR-061). That
            # is a defect in the emitting code, not a transport problem, and it
            # must dead-letter rather than retry.
            return error
        return None


class RedisEventStream:
    """Reads envelopes from Redis Streams. Implements :class:`EventStream`.

    Parameters
    ----------
    client
        An ``redis.asyncio.Redis``, injected for the same reason as above.
    aggregate_types
        Which streams this consumer reads. Named as aggregate types rather than
        as keys, so a consumer never spells a Redis key and the namespace stays
        an operational decision.
    group
        The logical consumer's name. Every process serving that consumer shares
        it, which is what makes the work divide rather than duplicate.
    consumer
        This process's name within the group. Must be distinct per process:
        two processes sharing one name share a pending list, and a restart then
        looks like a live consumer to ``XAUTOCLAIM``.
    supported_versions
        Envelope schema versions this consumer understands (ADR-061). When given,
        an envelope declaring anything else raises rather than being parsed on
        the assumption that the payload is close enough.

    Notes
    -----
    ``read`` polls and returns; it never blocks waiting for work. A stream that
    blocked would take the polling decision away from the consumer, and would
    make a replay's duration a function of the transport rather than of the data
    (ADR-069).
    """

    __slots__ = (
        "_client",
        "_consumer",
        "_cursor",
        "_group",
        "_keys",
        "_namespace",
        "_supported_versions",
    )

    def __init__(  # noqa: PLR0913 - each names a distinct collaborator, none is a flag
        self,
        client: Redis,
        *,
        aggregate_types: Sequence[str],
        group: str,
        consumer: str,
        namespace: str = DEFAULT_NAMESPACE,
        group_namespace: str = DEFAULT_GROUP_NAMESPACE,
        supported_versions: frozenset[int] | None = None,
    ) -> None:
        """Bind the stream to a client, a set of streams and a group identity."""
        if not aggregate_types:
            raise ConfigurationError(
                "a stream with no aggregate types would poll nothing and always look idle"
            )
        if not group or not consumer:
            raise ConfigurationError("group and consumer names are required")

        self._client = client
        self._namespace = namespace
        self._keys = tuple(stream_key(name, namespace=namespace) for name in aggregate_types)
        self._group = f"{group_namespace}:{group}"
        self._consumer = consumer
        self._supported_versions = supported_versions
        self._cursor = 0

    @property
    def group(self) -> str:
        """Return the fully qualified consumer group name."""
        return self._group

    @property
    def keys(self) -> tuple[str, ...]:
        """Return the stream keys this consumer reads, in declaration order."""
        return self._keys

    async def ensure_group(self) -> None:
        """Create the consumer group on every stream, idempotently.

        The group is created at id ``0`` rather than ``$``. Starting at ``$``
        would silently skip everything already buffered, which is indistinguishable
        from losing it; starting at ``0`` re-offers entries the ledger (ADR-065)
        is there to absorb. Given the choice, redeliver.

        ``MKSTREAM`` creates the stream if the relay has not written to it yet,
        so a consumer may legitimately start before its first producer.
        """
        for key in self._keys:
            try:
                await self._client.xgroup_create(key, self._group, id="0", mkstream=True)
            except redis_errors.ResponseError as error:
                if _BUSY_GROUP not in str(error):
                    raise _translate(error) from error
            except redis_errors.RedisError as error:
                raise _translate(error) from error

    async def read(self, *, limit: int) -> Sequence[Delivery]:
        """Return up to ``limit`` deliveries across all subscribed streams.

        Streams are read one at a time with a shrinking budget rather than in a
        single ``XREADGROUP``. ``COUNT`` is per stream, so one call with N
        streams can return N x limit entries -- and discarding the excess would
        strand them in the pending list, read but never handed to anyone.

        The stream examined first rotates on each call. Without that, a busy
        first stream would starve every stream after it for as long as it stayed
        busy, which is a stall that only appears under load.
        """
        if limit <= 0:
            raise ValidationError("limit must be positive", limit=limit)

        deliveries: list[Delivery] = []
        for key in self._rotated_keys():
            remaining = limit - len(deliveries)
            if remaining <= 0:
                break
            deliveries.extend(await self._read_one(key, remaining))
        return deliveries

    async def _read_one(self, key: str, limit: int) -> list[Delivery]:
        """Read up to ``limit`` new entries from a single stream."""
        try:
            response = await self._client.xreadgroup(
                self._group,
                self._consumer,
                {key: ">"},
                count=limit,
                block=None,
                noack=False,
            )
        except redis_errors.RedisError as error:
            raise _translate(error) from error

        return [
            self._to_delivery(stream, entry_id, fields)
            for stream, entry_id, fields in _iter_entries(response)
        ]

    async def acknowledge(self, tokens: Sequence[AckToken]) -> int:
        """Confirm the deliveries identified by ``tokens``, returning how many.

        Called after the consumer's transaction commits, never before (ADR-065).

        A token this stream did not issue raises rather than being ignored.
        Ignoring it would report a smaller number than the caller acknowledged
        and leave the entry pending forever, and the caller would have no way to
        tell that from a redelivery.
        """
        by_stream: dict[str, list[str]] = {}
        for token in tokens:
            ack = self._require_own_token(token)
            by_stream.setdefault(ack.stream, []).append(ack.entry_id)

        acknowledged = 0
        for stream, entry_ids in by_stream.items():
            try:
                acknowledged += int(await self._client.xack(stream, self._group, *entry_ids))
            except redis_errors.RedisError as error:
                raise _translate(error) from error
        return acknowledged

    async def pending(self) -> int:
        """Return how many entries are delivered to this group but not acknowledged.

        Summed across streams. This is the consumer-lag signal ADR-035 requires,
        and it is on the port rather than being a Redis detail because a replay
        adapter can answer it as truthfully as a broker can.
        """
        total = 0
        for key in self._keys:
            try:
                summary = await self._client.xpending(key, self._group)
            except redis_errors.ResponseError as error:
                if _NO_GROUP in str(error):
                    raise ConfigurationError(
                        "consumer group does not exist; call ensure_group() before reading",
                        stream=key,
                        group=self._group,
                    ) from error
                raise _translate(error) from error
            except redis_errors.RedisError as error:
                raise _translate(error) from error
            total += int(summary["pending"])
        return total

    async def reclaim(self, *, min_idle: timedelta, limit: int = 100) -> Sequence[Delivery]:
        """Take over entries this group holds but has not acknowledged.

        Crash recovery for a consumer that died holding deliveries. Deliberately
        **not** on the :class:`EventStream` port: it is a supervisor's decision
        about a process that has stopped, and putting it on the port would push a
        leasing concept into replay, where nothing can die.

        Because it is explicit, entries held by a dead consumer stay held until
        something calls this. That is a latency cliff, not a loss -- the outbox
        remains the record (ADR-062) -- and it is stated here rather than hidden
        behind an automatic reclaim inside ``read``.
        """
        if limit <= 0:
            raise ValidationError("limit must be positive", limit=limit)
        idle_ms = int(min_idle.total_seconds() * 1000)
        if idle_ms <= 0:
            raise ValidationError(
                "min_idle must be positive; a zero threshold reclaims entries a live "
                "consumer is still working on",
                min_idle=str(min_idle),
            )

        deliveries: list[Delivery] = []
        for key in self._keys:
            remaining = limit - len(deliveries)
            if remaining <= 0:
                break
            try:
                response = await self._client.xautoclaim(
                    key, self._group, self._consumer, idle_ms, start_id="0-0", count=remaining
                )
            except redis_errors.RedisError as error:
                raise _translate(error) from error
            deliveries.extend(
                self._to_delivery(key, entry_id, fields)
                for entry_id, fields in _iter_claimed(response)
            )
        return deliveries

    def _rotated_keys(self) -> tuple[str, ...]:
        """Return the streams to poll, starting one further along than last time."""
        start = self._cursor % len(self._keys)
        self._cursor = start + 1
        return self._keys[start:] + self._keys[:start]

    def _require_own_token(self, token: AckToken) -> RedisAck:
        """Narrow an opaque token to one this stream issued, or raise."""
        if not isinstance(token, RedisAck):
            raise ValidationError(
                "acknowledge received a token this stream did not issue",
                actual_type=type(token).__name__,
            )
        if token.stream not in self._keys:
            raise ValidationError(
                "acknowledge received a token for a stream this consumer does not read",
                stream=token.stream,
            )
        return token

    def _to_delivery(self, stream: str, entry_id: str, fields: Mapping[str, str]) -> Delivery:
        """Turn one stream entry into a :class:`Delivery`, or refuse it loudly."""
        document = fields.get(ENVELOPE_FIELD)
        if document is None:
            raise ValidationError(
                "stream entry carries no envelope field",
                stream=stream,
                entry_id=entry_id,
                field=ENVELOPE_FIELD,
                present=sorted(fields),
            )

        try:
            envelope = EventEnvelope.from_json(
                document, supported_versions=self._supported_versions
            )
        except DhruvaError as error:
            # Re-raised unchanged so a caller can still distinguish an unsupported
            # version from a corrupt payload. The coordinates are attached to the
            # error rather than written to a log here, for two reasons: this module
            # does not get to decide how serious a caller's failure is, and a
            # logging call inside an exception handler can itself raise -- which
            # replaces the error being reported with the failure to report it.
            error.context.setdefault("stream", stream)
            error.context.setdefault("entry_id", entry_id)
            raise
        except (ValueError, TypeError, KeyError) as error:
            raise ValidationError(
                "stream entry is not a readable envelope",
                stream=stream,
                entry_id=entry_id,
                reason=str(error),
            ) from error

        return Delivery(envelope=envelope, ack_token=RedisAck(stream=stream, entry_id=entry_id))


def _translate(error: redis_errors.RedisError) -> DhruvaError:
    """Map a redis-py exception onto the ADR-038 taxonomy.

    The mapping is deliberate rather than incidental. ``redis.ConnectionError``
    does *not* inherit from the builtin ``ConnectionError``, so without this
    every Redis failure would reach :func:`classify` as an unrecognised error and
    be retried by its default rather than by a decision anyone made.

    Everything here is retryable. A refused write is never dead-lettered on the
    strength of a broker's mood: ADR-062 states which way to be wrong, and a
    duplicate costs less than a lost event about capital. A payload that is
    genuinely unacceptable is refused before it reaches Redis, by
    :func:`stream_key` and by the envelope's own encoder.
    """
    if isinstance(error, redis_errors.AuthenticationError | redis_errors.AuthorizationError):
        return ConfigurationError(
            "Redis rejected the credentials this process was given", reason=str(error)
        )
    if isinstance(error, redis_errors.TimeoutError):
        return UpstreamTimeoutError("Redis did not answer in time", reason=str(error))
    if isinstance(error, redis_errors.ConnectionError):
        return UpstreamUnavailableError("Redis is unreachable", reason=str(error))
    return ExternalServiceError("Redis refused the command", reason=str(error))


def _iter_entries(response: object) -> Iterator[tuple[str, str, dict[str, str]]]:
    """Yield ``(stream, entry_id, fields)`` from an ``XREADGROUP`` reply.

    redis-py returns a different shape under RESP2 and RESP3 -- a list of
    ``[key, entries]`` pairs, or a mapping of key to a *singleton list of*
    entry lists. The protocol is a property of the injected client, which this
    adapter does not own, so both are accepted. Anything else raises: silently
    returning nothing for an unrecognised reply would look exactly like an idle
    stream, and a bus that appears idle while events accumulate is the failure
    that is hardest to notice.
    """
    if response is None:
        return
    if isinstance(response, dict):
        for key, groups in response.items():
            for entries in groups:
                yield from _iter_stream_entries(_text(key), entries)
        return
    if isinstance(response, list | tuple):
        for item in response:
            key, entries = item
            yield from _iter_stream_entries(_text(key), entries)
        return
    raise ExternalServiceError(
        "unrecognised XREADGROUP reply shape", actual_type=type(response).__name__
    )


def _iter_stream_entries(stream: str, entries: object) -> Iterator[tuple[str, str, dict[str, str]]]:
    """Yield the entries of one stream, skipping the tombstones Redis may return."""
    if entries is None:
        return
    if not isinstance(entries, list | tuple):
        raise ExternalServiceError(
            "unrecognised stream entry list", stream=stream, actual_type=type(entries).__name__
        )
    for entry_id, fields in entries:
        # A trimmed-away entry that a consumer still holds is reported as a pair
        # of nulls. It is not an entry and there is nothing to deliver.
        if entry_id is None:
            continue
        yield stream, _text(entry_id), _fields(fields)


def _iter_claimed(response: object) -> Iterator[tuple[str, dict[str, str]]]:
    """Yield ``(entry_id, fields)`` from an ``XAUTOCLAIM`` reply.

    Redis 6.2 replies with ``[cursor, entries]`` and Redis 7 added a third
    element listing ids that no longer exist. Both are read by position, so the
    adapter works across the versions an operator may actually be running.
    """
    if not isinstance(response, list | tuple) or len(response) < _XAUTOCLAIM_ELEMENTS:
        raise ExternalServiceError(
            "unrecognised XAUTOCLAIM reply shape", actual_type=type(response).__name__
        )
    entries = response[1]
    if entries is None:
        return
    for entry_id, fields in entries:
        if entry_id is None:
            continue
        yield _text(entry_id), _fields(fields)


def _fields(fields: object) -> dict[str, str]:
    """Decode one entry's field map to text."""
    if not isinstance(fields, dict):
        raise ExternalServiceError(
            "stream entry fields are not a mapping", actual_type=type(fields).__name__
        )
    return {_text(name): _text(value) for name, value in fields.items()}


def _text(value: Any) -> str:
    """Decode a redis reply element to ``str``.

    The client may or may not have been constructed with ``decode_responses``,
    and this adapter does not own that decision. Both are accepted; anything
    that is neither ``bytes`` nor ``str`` is a reply this code does not
    understand and is refused rather than coerced with ``str()``.
    """
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, str):
        return value
    raise ExternalServiceError(
        "redis reply element is neither bytes nor str", actual_type=type(value).__name__
    )
