"""Domain layer.

Entities, value objects, domain services, domain events and PORTS.

This layer performs no I/O and imports no framework. It may import only
``dhruva.shared`` and the standard library. Enforced by ADR-001 layering
and the import-linter contract ``Clean Architecture layers``.
"""

from dhruva.contexts.intelligence.domain.archive import (
    ArchivedNewsItem,
    NewsAnalysis,
    NewsArchiveWrite,
    NewsRevision,
    content_revision,
)
from dhruva.contexts.intelligence.domain.digest import (
    DIGEST_REVISION,
    MAX_ITEMS_PER_INSTRUMENT,
    DigestEntry,
    DigestSection,
    WatchlistDigest,
    build_digest,
)
from dhruva.contexts.intelligence.domain.entity_linking import (
    ENTITY_LINKING_REVISION,
    FORMER_NAME_GRACE,
    EntityLinkResult,
    EntityMatch,
    HistoricalName,
    LinkableInstrument,
    MatchKind,
    MatchState,
    link_entities,
)
from dhruva.contexts.intelligence.domain.events import (
    EVENT_CLASSIFICATION_REVISION,
    EventCategory,
    EventClassification,
    classify_event,
    event_precedence,
)
from dhruva.contexts.intelligence.domain.news import (
    NEWS_IDENTITY_REVISION,
    DeduplicationDecision,
    DeduplicationLedger,
    DeduplicationRule,
    NewsFingerprints,
    NewsItem,
    NewsItemIdentity,
    NewsSource,
    NewsSourceTier,
    PermittedText,
    canonical_url,
    normalise_headline,
    significant_tokens,
)
from dhruva.contexts.intelligence.domain.ports import IntelligenceUnitOfWork, NewsStore
from dhruva.contexts.intelligence.domain.search import (
    DEFAULT_BATCH_SIZE,
    MAX_BATCH_SIZE,
    MAX_PHRASE_CHARACTERS,
    MAX_PHRASES_PER_INSTRUMENT,
    MIN_BATCH_SIZE,
    MIN_SINGLE_TOKEN_CHARACTERS,
    SEARCH_PLAN_REVISION,
    PhraseRejection,
    RejectedPhrase,
    SearchBatch,
    SearchPhrase,
    SearchPlan,
    UnqueryableInstrument,
    plan_search_phrases,
)
from dhruva.contexts.intelligence.domain.sentiment import (
    SENTIMENT_RULESET_REVISION,
    AbstentionReason,
    SentimentLabel,
    SentimentResult,
    evaluate_sentiment,
)
from dhruva.contexts.intelligence.domain.sources import (
    NewsFetchResult,
    SourceHealth,
    SourceStatus,
)

__all__ = [
    "DEFAULT_BATCH_SIZE",
    "DIGEST_REVISION",
    "ENTITY_LINKING_REVISION",
    "EVENT_CLASSIFICATION_REVISION",
    "FORMER_NAME_GRACE",
    "MAX_BATCH_SIZE",
    "MAX_ITEMS_PER_INSTRUMENT",
    "MAX_PHRASES_PER_INSTRUMENT",
    "MAX_PHRASE_CHARACTERS",
    "MIN_BATCH_SIZE",
    "MIN_SINGLE_TOKEN_CHARACTERS",
    "NEWS_IDENTITY_REVISION",
    "SEARCH_PLAN_REVISION",
    "SENTIMENT_RULESET_REVISION",
    "AbstentionReason",
    "ArchivedNewsItem",
    "DeduplicationDecision",
    "DeduplicationLedger",
    "DeduplicationRule",
    "DigestEntry",
    "DigestSection",
    "EntityLinkResult",
    "EntityMatch",
    "EventCategory",
    "EventClassification",
    "HistoricalName",
    "IntelligenceUnitOfWork",
    "LinkableInstrument",
    "MatchKind",
    "MatchState",
    "NewsAnalysis",
    "NewsArchiveWrite",
    "NewsFetchResult",
    "NewsFingerprints",
    "NewsItem",
    "NewsItemIdentity",
    "NewsRevision",
    "NewsSource",
    "NewsSourceTier",
    "NewsStore",
    "PermittedText",
    "PhraseRejection",
    "RejectedPhrase",
    "SearchBatch",
    "SearchPhrase",
    "SearchPlan",
    "SentimentLabel",
    "SentimentResult",
    "SourceHealth",
    "SourceStatus",
    "UnqueryableInstrument",
    "WatchlistDigest",
    "build_digest",
    "canonical_url",
    "classify_event",
    "content_revision",
    "evaluate_sentiment",
    "event_precedence",
    "link_entities",
    "normalise_headline",
    "plan_search_phrases",
    "significant_tokens",
]
