"""Narrow offline mapper contract; provider transport remains out of scope."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, runtime_checkable

from dhruva.ingest.historical_dataset import ImportDecision, preflight_dataset
from dhruva.ingest.synthetic_historical_dataset import generate_synthetic_dataset

__all__ = [
    "CanonicalCsvMapper",
    "DatasetMapper",
    "MappingResult",
    "SyntheticFixtureMapper",
]


@dataclass(frozen=True, slots=True)
class MappingResult:
    """Canonical delivery selected or generated by one versioned mapper."""

    mapper_id: str
    mapping_revision: str
    manifest_path: Path
    import_decision: ImportDecision
    dataset_fingerprint: str


@runtime_checkable
class DatasetMapper(Protocol):
    """Map an offline source path into the canonical manifest/file contract."""

    mapper_id: str
    mapping_revision: str

    def map(self, source: Path, *, destination: Path | None = None) -> MappingResult:
        """Return a canonical delivery without network access."""
        ...


class CanonicalCsvMapper:
    """Identity mapper for deliveries already using DHRUVA's exact CSV schemas."""

    mapper_id = "canonical_csv"
    mapping_revision = "canonical_csv_v1"

    def map(self, source: Path, *, destination: Path | None = None) -> MappingResult:
        """Validate and select an existing manifest; never copies or mutates bytes."""
        if destination is not None:
            raise ValueError("canonical CSV mapping does not copy an immutable delivery")
        report = preflight_dataset(source)
        return MappingResult(
            mapper_id=self.mapper_id,
            mapping_revision=self.mapping_revision,
            manifest_path=source.resolve(),
            import_decision=report.import_decision,
            dataset_fingerprint=report.dataset_fingerprint,
        )


class SyntheticFixtureMapper:
    """Generate the canonical TEST DATA pack through the same mapper seam."""

    mapper_id = "synthetic_fixture"
    mapping_revision = "synthetic_fixture_v1"

    def map(self, source: Path, *, destination: Path | None = None) -> MappingResult:
        """Generate into ``destination`` (or ``source``) and preflight the result."""
        root = destination or source
        manifest = generate_synthetic_dataset(root)
        report = preflight_dataset(manifest)
        return MappingResult(
            mapper_id=self.mapper_id,
            mapping_revision=self.mapping_revision,
            manifest_path=manifest.resolve(),
            import_decision=report.import_decision,
            dataset_fingerprint=report.dataset_fingerprint,
        )
