"""SQLAlchemy models. Persistence shape only.

These classes describe **rows**, not concepts. They carry no behaviour, no
invariants and no domain types, and nothing outside ``infrastructure`` ever sees
one (ADR-052).

The column types deliberately store primitives rather than domain objects here,
even though ``types.py`` provides `TypeDecorator`s that could do the conversion.
Keeping the model primitive means the mapper is the single place a conversion
happens, so a mapping regression has exactly one place to look -- and it keeps
the mapper independently benchmarkable, which ADR-036 requires.
"""

from __future__ import annotations

from datetime import date, datetime
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

__all__ = [
    "AuditLogModel",
    "Base",
    "CredentialModel",
    "DailySnapshotModel",
    "PrincipalModel",
    "PrincipalRoleModel",
    "RefreshTokenModel",
    "RoleModel",
    "RolePermissionModel",
    "example_tick_table",
]


class Base(DeclarativeBase):
    """Declarative base for every model in the platform.

    One base, so Alembic's autogenerate sees a single metadata collection and
    cannot silently miss a table that registered against a different one.
    """


class DailySnapshotModel(Base):
    """The ``daily_snapshot`` table.

    Demonstrates every convention a real table must follow: surrogate UUID
    primary key, ``account_id`` on every row (ADR-004), a ``version`` column for
    optimistic concurrency (ADR-057), money stored as ``BIGINT`` minor units with
    its currency alongside (ADR-042), and constraints that re-assert domain
    invariants at the database so a value arriving by any other route is still
    refused.
    """

    __tablename__ = "daily_snapshot"
    __table_args__ = (
        UniqueConstraint("account_id", "instrument_id", "trading_day", name="uq_daily_snapshot"),
        CheckConstraint("turnover_minor_units >= 0", name="ck_daily_snapshot_turnover"),
        CheckConstraint("close_scaled_units <> 0", name="ck_daily_snapshot_close"),
        CheckConstraint("version >= 1", name="ck_daily_snapshot_version"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    instrument_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    trading_day: Mapped[date] = mapped_column(Date, nullable=False)
    close_scaled_units: Mapped[int] = mapped_column(BigInteger, nullable=False)
    turnover_minor_units: Mapped[int] = mapped_column(BigInteger, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False)
    # `default` is applied by the ORM on insert; `server_default` is DDL and is
    # what the migration actually created. Declaring only the first left the
    # model's metadata disagreeing with the live schema, so
    # `alembic revision --autogenerate` proposed dropping the server default --
    # meaning the next migration anyone generated for an unrelated change would
    # have silently carried an ALTER removing it in production. Both are
    # declared: the ORM path and any writer that bypasses it must agree.
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


class CredentialModel(Base):
    """The ``credential`` table (ADR-070, ADR-020).

    Mirrors migration ``0007_credential`` column for column, including both
    server defaults and both check constraints. That exactness is not
    housekeeping: Alembic compares this metadata against the live schema, so a
    constraint declared in the migration and omitted here reads as drift, and the
    next autogenerated revision -- for some unrelated change -- would quietly
    carry a DROP for it. The worked example's ``version`` column records the same
    lesson in its own comment.

    What is deliberately absent is the row-level security policy. Metadata cannot
    express one, Alembic does not autogenerate one, and the migration owns it
    (ADR-074).

    The table holds no plaintext and no master key -- only the ciphertext and the
    wrapped data key, which is exactly what ADR-070 says a row stores.
    """

    __tablename__ = "credential"
    __table_args__ = (
        UniqueConstraint("account_id", "broker", name="uq_credential_account_broker"),
        CheckConstraint("version >= 1", name="ck_credential_version"),
        CheckConstraint("key_version >= 1", name="ck_credential_key_version"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    broker: Mapped[str] = mapped_column(String(32), nullable=False)
    wrapped_data_key: Mapped[bytes] = mapped_column(postgresql.BYTEA(), nullable=False)
    ciphertext: Mapped[bytes] = mapped_column(postgresql.BYTEA(), nullable=False)
    key_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )
    rotated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


class AuditLogModel(Base):
    """The ``audit_log`` table (ADR-071, plan §15.1).

    Mirrors migration ``0008_audit_log`` column for column, index for index and
    constraint for constraint, for the reason :class:`CredentialModel` records:
    Alembic compares this metadata against the live schema, so anything declared
    in the migration and omitted here reads as drift and the next autogenerated
    revision would quietly carry a DROP for it. On this table that DROP would be
    of evidence.

    Two things are deliberately absent, and both absences are the design:

    **No** ``version`` **column.** Optimistic concurrency (ADR-057) exists to
    make an ``UPDATE`` detect a lost update, and there is no ``UPDATE`` here --
    the database refuses one. A version column would imply an update path that
    does not exist.

    **No free-form column.** The domain record carries no structured payload and
    argues why at length; the table matches it. An audit log is read widely,
    which makes it the worst possible place for a secret to land (ADR-037).

    The append-only triggers and the row-level security policy live in the
    migration and cannot be expressed here -- metadata has no way to describe
    either, and Alembic does not autogenerate them (ADR-071, ADR-074). That means
    this class looks like an ordinary writable table and is not, which is exactly
    why nothing outside :class:`~...persistence.audit.AuditRepository` should
    reach for it.
    """

    __tablename__ = "audit_log"
    __table_args__ = (
        # Explicit character set: bare `btrim(x)` strips spaces only, which
        # would let a tab-only actor through a check meant to mirror the
        # domain's `.strip()`. See migration 0008 for the full note.
        CheckConstraint(r"btrim(actor, E' \t\n\r') <> ''", name="ck_audit_log_actor"),
        CheckConstraint(r"btrim(subject, E' \t\n\r') <> ''", name="ck_audit_log_subject"),
        CheckConstraint("recorded_at >= occurred_at", name="ck_audit_log_ordering"),
        Index("ix_audit_log_account", "account_id"),
        Index("ix_audit_log_occurred_at", "occurred_at"),
        Index("ix_audit_log_action", "action"),
        Index("ix_audit_log_correlation", "correlation_id"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    actor: Mapped[str] = mapped_column(Text, nullable=False)
    # Text rather than a PostgreSQL ENUM. The action set has already grown once
    # -- ADR-071 added CREDENTIAL_READ -- and every future growth would otherwise
    # be an ALTER TYPE that takes a lock on a table nothing may rewrite. The
    # domain enum is the authority on the permitted values; a migration is not
    # the place to also enforce it.
    action: Mapped[str] = mapped_column(Text, nullable=False)
    subject: Mapped[str] = mapped_column(Text, nullable=False)
    outcome: Mapped[str] = mapped_column(Text, nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    correlation_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)


class PrincipalModel(Base):
    """The ``principal`` table (ADR-072, ADR-073).

    Mirrors migration ``0010_principal`` column for column, index for index and
    constraint for constraint, for the reason :class:`CredentialModel` records.

    ``password_hash`` is text and ``totp_secret`` is bytes, and the asymmetry is
    the design rather than an inconsistency: a password hash is one-way and needs
    no key, while a TOTP secret is shared symmetric key material the server must
    be able to recompute codes from, so it is sealed through ADR-070's envelope
    exactly as a broker credential is. The migration argues both at length.

    There is no ``totp_enrolled`` column. Enrolment is ``totp_secret IS NOT
    NULL``, and a boolean asserting the same fact is a boolean that can disagree
    with it -- which, because ADR-073 gates the order permission on enrolment,
    would mean granting order placement to an account with no working second
    factor.
    """

    __tablename__ = "principal"
    __table_args__ = (
        UniqueConstraint("subject", name="uq_principal_subject"),
        UniqueConstraint("id", "account_id", name="uq_principal_id_account"),
        CheckConstraint(r"btrim(subject, E' \t\n\r') <> ''", name="ck_principal_subject"),
        CheckConstraint(
            r"btrim(password_hash, E' \t\n\r') <> ''", name="ck_principal_password_hash"
        ),
        CheckConstraint("version >= 1", name="ck_principal_version"),
        CheckConstraint("updated_at >= created_at", name="ck_principal_timestamps"),
        CheckConstraint(
            "(totp_secret IS NULL) = (totp_wrapped_key IS NULL)", name="ck_principal_totp_pair"
        ),
        Index("ix_principal_account", "account_id"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    subject: Mapped[str] = mapped_column(Text, nullable=False)
    # The argon2 encoded form, which carries its own algorithm, parameters and
    # salt. Stored as given and never parsed here: the hasher owns the format,
    # and a persistence layer that understood it would be a second place the
    # parameters could be decided.
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    totp_secret: Mapped[bytes | None] = mapped_column(postgresql.BYTEA(), nullable=True)
    totp_wrapped_key: Mapped[bytes | None] = mapped_column(postgresql.BYTEA(), nullable=True)
    disabled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


class RefreshTokenModel(Base):
    """The ``refresh_token`` table (ADR-072).

    Mirrors migration ``0009_refresh_token`` column for column, index for index
    and constraint for constraint.

    The row-level security policy is deliberately absent, as it is on every other
    model: metadata cannot express one and Alembic does not autogenerate one, so
    the migration owns it (ADR-074).

    No ``version`` column, and unlike :class:`AuditLogModel` that is not because
    the row is immutable. A refresh token *is* updated -- rotation stamps
    ``replaced_by`` and revocation stamps ``revoked_at`` -- but both are
    **conditional** updates that carry their own concurrency control in the
    ``WHERE`` clause: rotation only succeeds against a row that is not yet
    replaced, which is precisely the lost-update check ADR-057's version column
    would otherwise provide. A version column here would be a second mechanism
    for a race the first one already loses correctly.
    """

    __tablename__ = "refresh_token"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_refresh_token_hash"),
        CheckConstraint("expires_at > issued_at", name="ck_refresh_token_lifetime"),
        CheckConstraint(
            "(parent_token_id IS NOT NULL) OR (lineage_id = id)",
            name="ck_refresh_token_lineage_root",
        ),
        Index("ix_refresh_token_account", "account_id"),
        Index("ix_refresh_token_principal", "principal_id"),
        Index("ix_refresh_token_lineage", "lineage_id"),
        Index("ix_refresh_token_parent", "parent_token_id"),
        Index("ix_refresh_token_expires_at", "expires_at"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    principal_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    # Every token in a rotation chain carries the same value, so revoking a
    # compromised family is one statement against one index rather than a
    # recursive walk that is slowest exactly when it matters most.
    lineage_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    # The hash, never the token. A stolen database must not yield a usable
    # credential, which is the same argument ADR-070 makes about the credential
    # table one step earlier.
    token_hash: Mapped[bytes] = mapped_column(postgresql.BYTEA(), nullable=False)
    parent_token_id: Mapped[UUID | None] = mapped_column(
        postgresql.UUID(as_uuid=True), nullable=True
    )
    issued_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    replaced_by: Mapped[UUID | None] = mapped_column(postgresql.UUID(as_uuid=True), nullable=True)


class RoleModel(Base):
    """The ``role`` table (ADR-073).

    Mirrors migration ``0011_authorisation`` column for column and constraint for
    constraint.

    A role with no permissions is a valid row, and that is the reason this table
    is separate from :class:`RolePermissionModel` rather than inferred from it.
    Deny-by-default means the empty role is the *default* state -- what a new
    operator holds before anybody decides what they may do -- so it has to be
    storable.

    The primary key is composite because a role name is unique within a tenant
    rather than across the platform: two accounts may each have an "operator".
    """

    __tablename__ = "role"
    __table_args__ = (
        CheckConstraint(r"btrim(name, E' \t\n\r') <> ''", name="ck_role_name"),
        CheckConstraint("updated_at >= created_at", name="ck_role_timestamps"),
        CheckConstraint("version >= 1", name="ck_role_version"),
    )

    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    name: Mapped[str] = mapped_column(Text, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


class RolePermissionModel(Base):
    """The ``role_permission`` table (ADR-073).

    One row means the role holds the permission; no row means it does not. There
    is deliberately no ``granted`` boolean: deny-by-default already supplies the
    negative, and a column would give one fact two representations that can
    disagree.

    ``permission`` is text rather than a PostgreSQL enum, for the reason
    :class:`AuditLogModel` records about ``action``: the value set grows, and the
    domain enum is the authority on which values are permitted.
    """

    __tablename__ = "role_permission"
    __table_args__ = (
        ForeignKeyConstraint(
            ("account_id", "role_name"),
            ("role.account_id", "role.name"),
            name="fk_role_permission_role",
            ondelete="CASCADE",
        ),
        CheckConstraint(r"btrim(permission, E' \t\n\r') <> ''", name="ck_role_permission_value"),
        CheckConstraint(r"btrim(granted_by, E' \t\n\r') <> ''", name="ck_role_permission_actor"),
    )

    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    role_name: Mapped[str] = mapped_column(Text, primary_key=True)
    permission: Mapped[str] = mapped_column(Text, primary_key=True)
    granted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # The second copy of a fact the audit log also holds, kept because the two
    # answer different questions: the log answers "what happened, in order", this
    # answers "who is responsible for the authority held right now".
    granted_by: Mapped[str] = mapped_column(Text, nullable=False)


class PrincipalRoleModel(Base):
    """The ``principal_role`` table (ADR-073).

    ``principal_id`` alone is the primary key, which is how "one role per
    principal" is enforced rather than merely intended. ADR-073's ``Role`` is
    singular and carries one name; two rows per principal would make "which role
    does this principal hold?" a question with two answers and no rule for
    combining them.
    """

    __tablename__ = "principal_role"
    __table_args__ = (
        ForeignKeyConstraint(
            ("account_id", "role_name"),
            ("role.account_id", "role.name"),
            name="fk_principal_role_role",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ("principal_id", "account_id"),
            ("principal.id", "principal.account_id"),
            name="fk_principal_role_principal",
            ondelete="CASCADE",
        ),
        CheckConstraint(r"btrim(assigned_by, E' \t\n\r') <> ''", name="ck_principal_role_actor"),
        Index("ix_principal_role_role", "account_id", "role_name"),
    )

    principal_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    role_name: Mapped[str] = mapped_column(Text, nullable=False)
    assigned_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    assigned_by: Mapped[str] = mapped_column(Text, nullable=False)


# --------------------------------------------------------------------------- #
# The ORM-bypass path (ADR-054)
# --------------------------------------------------------------------------- #

#: Worked example of an append-only timeseries table.
#:
#: A Core ``Table``, deliberately **not** a declarative model. There is no ORM
#: class because there is nothing to map: rows on this path have no identity, no
#: lifecycle and no invariant beyond their column constraints, and giving them a
#: class would invite exactly the domain coupling ADR-054 forbids. Writes go
#: through ``PostgresTimeSeriesStorage`` in the ``timeseries`` package.
#:
#: It is registered in ``Base.metadata`` all the same, because Alembic compares
#: metadata against the live schema. A table created by a migration and absent
#: from metadata is drift: autogenerate would propose dropping it, and the next
#: migration generated for an unrelated change would carry that DROP along.
#: Declaring the schema and mapping it to a class are different things, and only
#: the second is what ADR-052 rules out.
example_tick_table = Table(
    "example_tick",
    Base.metadata,
    Column("instrument_id", postgresql.UUID(as_uuid=True), nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    Column("price_scaled_units", BigInteger, nullable=False),
    Column("quantity_units", BigInteger, nullable=False),
    # No primary key. Ticks are observations, not entities: the same instrument
    # can legitimately trade twice at the same microsecond, and inventing a
    # surrogate key to forbid that would be the model overruling the market.
    Index("ix_example_tick_instrument_observed", "instrument_id", "observed_at"),
    CheckConstraint("quantity_units > 0", name="ck_example_tick_quantity"),
)
