"""SQLAlchemy models. Persistence shape only.

These classes describe **rows**, not concepts. They carry no behaviour, no
invariants and no domain types, and nothing outside ``infrastructure`` ever sees
one (ADR-052).

The column types deliberately store primitives rather than domain objects here,
even though ``types.py`` provides `TypeDecorator`s that could do the conversion.
Keeping the model primitive means the mapper is the single place a conversion
happens, so a mapping regression has exactly one place to look -- and it keeps
the mapper independently benchmarkable, which ADR-036 requires.
"""

from __future__ import annotations

from datetime import date, datetime
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Index,
    Integer,
    String,
    Table,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

__all__ = ["Base", "CredentialModel", "DailySnapshotModel", "example_tick_table"]


class Base(DeclarativeBase):
    """Declarative base for every model in the platform.

    One base, so Alembic's autogenerate sees a single metadata collection and
    cannot silently miss a table that registered against a different one.
    """


class DailySnapshotModel(Base):
    """The ``daily_snapshot`` table.

    Demonstrates every convention a real table must follow: surrogate UUID
    primary key, ``account_id`` on every row (ADR-004), a ``version`` column for
    optimistic concurrency (ADR-057), money stored as ``BIGINT`` minor units with
    its currency alongside (ADR-042), and constraints that re-assert domain
    invariants at the database so a value arriving by any other route is still
    refused.
    """

    __tablename__ = "daily_snapshot"
    __table_args__ = (
        UniqueConstraint("account_id", "instrument_id", "trading_day", name="uq_daily_snapshot"),
        CheckConstraint("turnover_minor_units >= 0", name="ck_daily_snapshot_turnover"),
        CheckConstraint("close_scaled_units <> 0", name="ck_daily_snapshot_close"),
        CheckConstraint("version >= 1", name="ck_daily_snapshot_version"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    instrument_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    trading_day: Mapped[date] = mapped_column(Date, nullable=False)
    close_scaled_units: Mapped[int] = mapped_column(BigInteger, nullable=False)
    turnover_minor_units: Mapped[int] = mapped_column(BigInteger, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False)
    # `default` is applied by the ORM on insert; `server_default` is DDL and is
    # what the migration actually created. Declaring only the first left the
    # model's metadata disagreeing with the live schema, so
    # `alembic revision --autogenerate` proposed dropping the server default --
    # meaning the next migration anyone generated for an unrelated change would
    # have silently carried an ALTER removing it in production. Both are
    # declared: the ORM path and any writer that bypasses it must agree.
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


class CredentialModel(Base):
    """The ``credential`` table (ADR-070, ADR-020).

    Mirrors migration ``0007_credential`` column for column, including both
    server defaults and both check constraints. That exactness is not
    housekeeping: Alembic compares this metadata against the live schema, so a
    constraint declared in the migration and omitted here reads as drift, and the
    next autogenerated revision -- for some unrelated change -- would quietly
    carry a DROP for it. The worked example's ``version`` column records the same
    lesson in its own comment.

    What is deliberately absent is the row-level security policy. Metadata cannot
    express one, Alembic does not autogenerate one, and the migration owns it
    (ADR-074).

    The table holds no plaintext and no master key -- only the ciphertext and the
    wrapped data key, which is exactly what ADR-070 says a row stores.
    """

    __tablename__ = "credential"
    __table_args__ = (
        UniqueConstraint("account_id", "broker", name="uq_credential_account_broker"),
        CheckConstraint("version >= 1", name="ck_credential_version"),
        CheckConstraint("key_version >= 1", name="ck_credential_key_version"),
    )

    id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True)
    account_id: Mapped[UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    broker: Mapped[str] = mapped_column(String(32), nullable=False)
    wrapped_data_key: Mapped[bytes] = mapped_column(postgresql.BYTEA(), nullable=False)
    ciphertext: Mapped[bytes] = mapped_column(postgresql.BYTEA(), nullable=False)
    key_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )
    rotated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


# --------------------------------------------------------------------------- #
# The ORM-bypass path (ADR-054)
# --------------------------------------------------------------------------- #

#: Worked example of an append-only timeseries table.
#:
#: A Core ``Table``, deliberately **not** a declarative model. There is no ORM
#: class because there is nothing to map: rows on this path have no identity, no
#: lifecycle and no invariant beyond their column constraints, and giving them a
#: class would invite exactly the domain coupling ADR-054 forbids. Writes go
#: through ``PostgresTimeSeriesStorage`` in the ``timeseries`` package.
#:
#: It is registered in ``Base.metadata`` all the same, because Alembic compares
#: metadata against the live schema. A table created by a migration and absent
#: from metadata is drift: autogenerate would propose dropping it, and the next
#: migration generated for an unrelated change would carry that DROP along.
#: Declaring the schema and mapping it to a class are different things, and only
#: the second is what ADR-052 rules out.
example_tick_table = Table(
    "example_tick",
    Base.metadata,
    Column("instrument_id", postgresql.UUID(as_uuid=True), nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    Column("price_scaled_units", BigInteger, nullable=False),
    Column("quantity_units", BigInteger, nullable=False),
    # No primary key. Ticks are observations, not entities: the same instrument
    # can legitimately trade twice at the same microsecond, and inventing a
    # surrogate key to forbid that would be the model overruling the market.
    Index("ix_example_tick_instrument_observed", "instrument_id", "observed_at"),
    CheckConstraint("quantity_units > 0", name="ck_example_tick_quantity"),
)
